server:
  port: 1000
eureka:
  instance:
    hostname:eureka_serve
  client:
    registerWithEureka: false
    fetchRegistry: false  # 禁止当前注册中心拉取注册服务订单
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/ #注册中心地址 http://localhost:1000
spring:
  application:
    name: EUREKA-SERVE