eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9998
spring:
  application:
    name: config-serve
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1653152776/aigou-config.git
          username: 1653152776
          password: wangyilin19980503
