server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: ZUUL-GATEWAY
zuul:
  routes:
    palt_serve: /employee/** #以/user开头的所有路径都转发给user-provider进行处理
  ignored-services: "*"
  prefix: "/aigou" #忽略掉服务名访问方式 使用上面/user的方式来访问